import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Perfil de usuario",
  description: "Generated by create next app",
};



export default function ProfilePage(params: any) {

    return (
        <h1>Perfil del usuario</h1>
    )
    
}