import { Metadata } from "next";
import { FaUserCircle } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Perfil de usuario",
  description: "Generated by create next app",
};

export default function ProfilePage(params: any) {

  return (
    <div className="mx-auto max-w-xl p-4 gap-2 flex flex-col">
      <div className="rounded-xl bg-surface-container shadow p-7 flex flex-col justify-center items-center gap-3">
        <FaUserCircle className="text-9xl" />
        <p className="text-xl">Andres Rodriguez</p>
      </div>

      <h3 className="px-2">Datos personales</h3>
      <div className="rounded-xl bg-surface-container shadow p-7 grid grid-cols-4 gap-4">
        {/* Nombre */}
        <label htmlFor="name">Nombre</label>
        <input className=" border col-span-3 rounded-lg border-on-surface-variant px-2" type="text" name="name" id="name" />
        {/* Edad */}
        <label htmlFor="age">Edad</label>
        <input className=" border col-span-3 rounded-lg border-on-surface-variant px-2" type="number" name="age" id="age" />
        {/* Sexo */}
        <label htmlFor="sex">Sexo</label>
        <select className=" border col-span-3 rounded-lg border-on-surface-variant px-2" name="sex" id="sex">
          <option value="M">Masculino</option>
          <option value="F">Femenino</option>
        </select>
      </div>

      <h3 className="px-2">Objetivos</h3>
      <div className="rounded-xl bg-surface-container shadow p-7">
        {/* Motivo */}
        <textarea rows={3} name="objective" id="objective" className="w-full border rounded-lg border-on-surface-variant p-3"/>
      </div>

      <h3 className="px-2">Disponibilidad horaria</h3>
      <div className="rounded-xl bg-surface-container shadow p-7">
        {/* Disponibilidad */}
        <textarea rows={3} name="availability" id="availability" className="w-full border rounded-lg border-on-surface-variant p-3" />
      </div>

      <div className="text-lg flex justify-center gap-4 p-4">
        <button className="rounded-lg bg-[#61ac67] p-2 px-6 text-on-primary">Guardar</button>
        <button className="rounded-lg bg-gray-400  p-2 px-6 text-on-primary">Cancelar</button>
      </div>
    </div>
  )

}