import { getProfileInfo } from "@/actions/profile";
import { Metadata } from "next";
import { FaUserCircle } from "react-icons/fa";
import ProfileForm from "./components/ProfileForm";

export const metadata: Metadata = {
  title: "Perfil de usuario",
  description: "Generated by create next app",
};

export default async function ProfilePage(params: any) {

  const response = await getProfileInfo()
  const { message, success, data: profile } = response 
  if (!profile) return <>Hubo un problema al cargar la sesion</>

  return (
    <ProfileForm profile={profile}/>
  )

}